# Generated by Django 4.0.4 on 2022-04-19 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0001_initial'),
        ('login', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.naturezaoperacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.grupofiscal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ban_padrao', to='cadastro.banco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ema_padrao', to='cadastro.email'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_padrao', to='cadastro.endereco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='site_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sit_padrao', to='cadastro.site'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tel_padrao', to='cadastro.telefone'),
        ),
        migrations.AddField(
            model_name='minhaempresa',
            name='m_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to='login.usuario'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='email',
            name='pessoa_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pessoa_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='banco',
            name='pessoa_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='transportadora_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='cadastro.transportadora'),
        ),
        migrations.AddField(
            model_name='minhaempresa',
            name='m_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minha_empresa', to='cadastro.empresa'),
        ),
    ]
