# Generated by Django 4.0.4 on 2022-04-19 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        ('compras', '0001_initial'),
        ('estoque', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cond_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_pagamento', to='vendas.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_fornecedor', to='cadastro.fornecedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compra_local_estoque', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_pedido', to='compras.orcamentocompra'),
        ),
    ]
